# Use an official Maven runtime as a parent image
FROM maven:3.9.9-eclipse-temurin-21 AS build

# Set the working directory to /app
WORKDIR /app

# Copy the pom.xml file to the working directory
COPY pom.xml .

# Download all dependencies defined in the pom.xml file
RUN mvn dependency:go-offline

# Copy the entire project source code to the working directory
COPY src/ .

# Build the application using Maven
RUN mvn package 

FROM gcr.io/distroless/java21-debian13

WORKDIR /app

COPY --from=build /app/target/App.jar .

CMD ["main.jar"]

