# Use an official Maven runtime as a parent image
FROM maven:3.9.9-eclipse-temurin-21 

# Set the working directory to /app
WORKDIR /app

# Copy the entire project source code to the working directory
COPY pom.xml .

# Download all dependencies defined in the pom.xml file
RUN mvn dependency:go-offline

COPY src/ .

# Build the application using Maven
RUN mvn package


# Set the command to run the application when the container starts
CMD ["java", "-jar", "App.jar"]

